# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客')], db_index=True, max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('params', models.JSONField(blank=True, default=dict, help_text='如 months / contest_ids', verbose_name='任务参数')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Celery 任务ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('contest_count', models.PositiveIntegerField(default=0, verbose_name='处理比赛数')),
                ('participation_count', models.PositiveIntegerField(default=0, verbose_name='入库记录数')),
                ('cheater_count', models.PositiveIntegerField(default=0, verbose_name='排除作弊数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('log', models.TextField(blank=True, verbose_name='执行日志')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='留空表示定时任务', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_jobs', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
            ],
            options={
                'verbose_name': '爬取任务',
                'verbose_name_plural': '爬取任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
