# Generated by Django 5.2.16 on 2026-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_beat_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后即便 beat 到点也不会触发爬取', verbose_name='启用自动爬取')),
                ('cf_count', models.PositiveIntegerField(default=20, help_text='最近 N 场（rated）', verbose_name='Codeforces 抓取场数')),
                ('atcoder_count', models.PositiveIntegerField(default=20, help_text='最近 N 场（rated）', verbose_name='AtCoder 抓取场数')),
                ('nowcoder_months_back', models.PositiveIntegerField(default=2, help_text='抓取最近 N 个月的比赛', verbose_name='牛客最近月数')),
                ('auto_crawl_hour', models.PositiveIntegerField(default=2, help_text='每日该小时(0-23)触发，分钟固定 00', verbose_name='自动爬取小时')),
            ],
            options={
                'verbose_name': '自动爬取配置',
                'verbose_name_plural': '自动爬取配置',
            },
        ),
    ]
