# Generated by Django 5.2.17 on 2026-08-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_swap_beat_to_auto_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlconfig',
            name='auto_crawl_interval_days',
            field=models.PositiveIntegerField(default=1, help_text='每隔 N 天自动触发一次（1~30），N=1 即每天', verbose_name='自动爬取间隔天数'),
        ),
        migrations.AlterField(
            model_name='crawlconfig',
            name='auto_crawl_hour',
            field=models.PositiveIntegerField(default=2, help_text='触发当天的小时(0-23)，分钟固定 00', verbose_name='自动爬取小时'),
        ),
    ]
