# Generated by Django 5.2.16 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_calendar_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客'), ('luogu', '洛谷')], db_index=True, max_length=20, verbose_name='平台'),
        ),
    ]
