# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='简称')),
                ('code', models.SlugField(help_text='URL 用的英文短标识，如 pku', unique=True, verbose_name='学校标识')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/', verbose_name='校徽')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cf_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Codeforces 平台系数')),
                ('atcoder_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='AtCoder 平台系数')),
                ('nowcoder_factor', models.DecimalField(decimal_places=3, default=0.8, max_digits=6, verbose_name='牛客 平台系数')),
                ('default_contest_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='比赛难度默认系数')),
                ('platform_weight', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, verbose_name='平台系数权重')),
                ('contest_weight', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, verbose_name='比赛系数权重')),
                ('recent_contest_limit', models.PositiveIntegerField(default=0, help_text='0 表示不限制', verbose_name='计分场次上限')),
                ('school', models.OneToOneField(blank=True, help_text='留空表示全局默认配置', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_config', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '积分系数配置',
                'verbose_name_plural': '积分系数配置',
            },
        ),
        migrations.CreateModel(
            name='SchoolAdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('proposed_school_name', models.CharField(blank=True, max_length=100, verbose_name='新建学校名称')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系方式')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='admin_apply/', verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已撤回')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('review_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_applications', to='schools.school', verbose_name='申请学校')),
            ],
            options={
                'verbose_name': '学校管理员申请',
                'verbose_name_plural': '学校管理员申请',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant', 'school'), name='uniq_pending_application')],
            },
        ),
    ]
