# Generated by Django 5.2.16 on 2026-08-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_scoreconfig_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminapplication',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_applications', to='schools.school', verbose_name='申请学校'),
        ),
    ]
