# Generated by Django 5.2.16 on 2026-08-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_schooladminapplication_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtCoderAffiliationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('raw_affiliation', models.CharField(db_index=True, help_text='AtCoder 榜单 Affiliation 原始写法', max_length=200, verbose_name='原始机构名')),
                ('canonical_name', models.CharField(blank=True, help_text='无对应学校时的归一化展示名', max_length=200, verbose_name='归一化名')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_aliases', to='schools.school', verbose_name='对应学校')),
            ],
            options={
                'verbose_name': 'AtCoder 机构别名',
                'verbose_name_plural': 'AtCoder 机构别名',
                'ordering': ['raw_affiliation'],
                'constraints': [models.UniqueConstraint(fields=('raw_affiliation',), name='uniq_raw_affiliation')],
            },
        ),
    ]
