# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客')], db_index=True, max_length=20, verbose_name='平台')),
                ('external_id', models.CharField(db_index=True, max_length=64, verbose_name='平台比赛ID')),
                ('name', models.CharField(max_length=255, verbose_name='比赛名称')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='比赛链接')),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（分钟）')),
                ('is_rated', models.BooleanField(db_index=True, default=False, verbose_name='计入平台 rating')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='付费比赛')),
                ('rated_source', models.CharField(blank=True, max_length=100, verbose_name='判定来源')),
                ('rated_comment', models.CharField(blank=True, max_length=255, verbose_name='判定说明')),
                ('series', models.CharField(blank=True, help_text='如 牛客周赛 / Div.2', max_length=100, verbose_name='赛事系列')),
                ('difficulty_factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='比赛难度系数')),
                ('problem_count', models.PositiveIntegerField(default=0, verbose_name='题目数')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='参赛人数')),
                ('valid_participant_count', models.PositiveIntegerField(default=0, verbose_name='有效参赛人数')),
                ('cheater_count', models.PositiveIntegerField(default=0, verbose_name='作弊账号数')),
                ('raw_meta', models.JSONField(blank=True, default=dict, verbose_name='原始元数据')),
                ('crawled_at', models.DateTimeField(blank=True, null=True, verbose_name='最近抓取时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['platform', '-start_time'], name='contests_co_platfor_a45fd3_idx'), models.Index(fields=['is_rated', 'is_paid'], name='contests_co_is_rate_758d74_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='uniq_platform_contest')],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handle', models.CharField(db_index=True, max_length=100, verbose_name='榜单账号标识')),
                ('handle_lower', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='小写标识')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='榜单昵称')),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='名次')),
                ('solved_count', models.IntegerField(blank=True, null=True, verbose_name='过题数')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('penalty_ms', models.BigIntegerField(blank=True, null=True, verbose_name='罚时（毫秒）')),
                ('rating_delta', models.IntegerField(blank=True, null=True, verbose_name='rating 变化')),
                ('old_rating', models.IntegerField(blank=True, null=True, verbose_name='赛前 rating')),
                ('new_rating', models.IntegerField(blank=True, null=True, verbose_name='赛后 rating')),
                ('is_excluded', models.BooleanField(db_index=True, default=False, verbose_name='排除出积分')),
                ('exclude_reason', models.CharField(blank=True, choices=[('', '未排除'), ('cheater', '平台标记作弊'), ('post_contest', '赛后补交'), ('unbound', '未绑定学生'), ('manual', '人工剔除')], default='', max_length=20, verbose_name='排除原因')),
                ('raw_display_name', models.CharField(blank=True, max_length=200, verbose_name='原始昵称')),
                ('score_detail', models.JSONField(blank=True, default=list, verbose_name='每题明细')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='平台特有字段')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='contests.contest', verbose_name='比赛')),
                ('platform_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='accounts.platformaccount', verbose_name='平台账号')),
            ],
            options={
                'verbose_name': '参赛记录',
                'verbose_name_plural': '参赛记录',
                'ordering': ['contest', 'rank'],
                'indexes': [models.Index(fields=['platform_account', '-created_at'], name='contests_pa_platfor_df604b_idx'), models.Index(fields=['is_excluded', 'contest'], name='contests_pa_is_excl_7a9910_idx')],
                'constraints': [models.UniqueConstraint(fields=('contest', 'handle_lower'), name='uniq_contest_handle')],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('index', models.CharField(help_text='A/B/C...', max_length=10, verbose_name='题号')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='题目名')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='平台题目ID')),
                ('full_score', models.IntegerField(blank=True, null=True, verbose_name='满分')),
                ('solved_count', models.PositiveIntegerField(default=0, verbose_name='通过人数')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='contests.contest', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['contest', 'index'],
                'constraints': [models.UniqueConstraint(fields=('contest', 'index'), name='uniq_contest_problem')],
            },
        ),
    ]
