# Generated by Django 5.2.17 on 2026-08-25 09:18

from django.db import migrations, models


DEFAULT_FACTORS = [
    # Codeforces：Div 越高难度越低，Educational 居中，Global 略高
    ("codeforces", "Div. 1", 1.5),
    ("codeforces", "Div. 2", 1.2),
    ("codeforces", "Div. 3", 1.0),
    ("codeforces", "Div. 4", 0.9),
    ("codeforces", "Educational", 1.1),
    ("codeforces", "Global", 1.3),
    # AtCoder：AGC > ARC > ABC
    ("atcoder", "AGC", 1.5),
    ("atcoder", "ARC", 1.2),
    ("atcoder", "ABC", 1.0),
    # 牛客：多校/挑战赛/寒假营 > 周赛 > 小白月赛 > 练习赛
    ("nowcoder", "牛客暑期多校训练营", 1.5),
    ("nowcoder", "牛客挑战赛", 1.3),
    ("nowcoder", "牛客寒假算法基础集训营", 1.3),
    ("nowcoder", "牛客周赛", 1.2),
    ("nowcoder", "牛客小白月赛", 1.0),
    ("nowcoder", "牛客练习赛", 0.9),
]


def seed_default_factors(apps, schema_editor):
    ContestDifficultyFactor = apps.get_model("contests", "ContestDifficultyFactor")
    for platform, series, factor in DEFAULT_FACTORS:
        ContestDifficultyFactor.objects.update_or_create(
            platform=platform, series=series, defaults={"factor": factor})


def unseed_default_factors(apps, schema_editor):
    ContestDifficultyFactor = apps.get_model("contests", "ContestDifficultyFactor")
    for platform, series, _ in DEFAULT_FACTORS:
        ContestDifficultyFactor.objects.filter(
            platform=platform, series=series).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestDifficultyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客')], db_index=True, max_length=20, verbose_name='平台')),
                ('series', models.CharField(db_index=True, max_length=100, verbose_name='比赛系列')),
                ('factor', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='难度系数')),
            ],
            options={
                'verbose_name': '比赛难度系数',
                'verbose_name_plural': '比赛难度系数',
                'ordering': ['platform', 'series'],
                'constraints': [models.UniqueConstraint(fields=('platform', 'series'), name='uniq_platform_series_difficulty')],
            },
        ),
        migrations.RunPython(seed_default_factors, unseed_default_factors),
    ]
