# Generated by Django 5.2.17 on 2026-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestdifficultyfactor_perf_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestdifficultyfactor',
            name='factor',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='难度系数（旧口径，保留展示）'),
        ),
    ]
