# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contests', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('scope', models.CharField(choices=[('school', '学校榜'), ('student', '个人榜')], db_index=True, max_length=20, verbose_name='榜单类型')),
                ('period', models.CharField(db_index=True, default='all', help_text='all / 2026 / 2026-08 等', max_length=20, verbose_name='统计周期')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='名次')),
                ('total_score', models.FloatField(default=0, verbose_name='总积分')),
                ('contest_count', models.PositiveIntegerField(default=0, verbose_name='参赛场次')),
                ('member_count', models.PositiveIntegerField(default=0, help_text='学校榜专用', verbose_name='统计人数')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('computed_at', models.DateTimeField(db_index=True, verbose_name='计算时间')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_snapshots', to='schools.school', verbose_name='学校')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rank_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '排行榜快照',
                'verbose_name_plural': '排行榜快照',
                'ordering': ['scope', 'period', 'rank'],
                'indexes': [models.Index(fields=['scope', 'period', 'rank'], name='ranking_ran_scope_ec08a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客')], db_index=True, max_length=20, verbose_name='平台')),
                ('base_score', models.FloatField(default=0, verbose_name='基础分')),
                ('platform_factor', models.FloatField(default=1, verbose_name='平台系数')),
                ('contest_factor', models.FloatField(default=1, verbose_name='比赛难度系数')),
                ('final_score', models.FloatField(db_index=True, default=0, verbose_name='最终积分')),
                ('formula', models.CharField(blank=True, max_length=255, verbose_name='计算公式快照')),
                ('contest_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='比赛时间')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_record', to='contests.participation', verbose_name='参赛记录')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_records', to='accounts.platformaccount', verbose_name='平台账号')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_records', to='schools.school', verbose_name='学校')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ['-contest_time'],
                'indexes': [models.Index(fields=['school', '-final_score'], name='ranking_sco_school__ea975d_idx'), models.Index(fields=['platform_account', '-contest_time'], name='ranking_sco_platfor_bb447d_idx')],
            },
        ),
    ]
