# Generated by Django 5.2.17 on 2026-08-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('year', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='赛季编号（年份）')),
                ('name', models.CharField(default='', max_length=50, verbose_name='赛季名称')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='结束时间')),
                ('stage', models.CharField(choices=[('upcoming', '未开始'), ('active', '进行中'), ('settling', '结算中'), ('ended', '已结束')], db_index=True, default='active', max_length=20, verbose_name='所处阶段')),
                ('rewards', models.JSONField(blank=True, default=list, help_text='如 [{title, desc, icon}]', verbose_name='奖励内容')),
                ('settle_at', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
            ],
            options={
                'verbose_name': '积分赛季',
                'verbose_name_plural': '积分赛季',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SeasonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('current_season', models.PositiveIntegerField(default=0, verbose_name='当前赛季年份')),
                ('auto_reset', models.BooleanField(default=True, verbose_name='自动年度重置')),
            ],
            options={
                'verbose_name': '赛季配置',
                'verbose_name_plural': '赛季配置',
            },
        ),
    ]
