# Generated by Django 5.2.16 on 2026-08-31 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_season_seasonconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('best_rank', models.PositiveIntegerField(verbose_name='历史最佳名次')),
                ('best_rank_score', models.FloatField(verbose_name='最佳名次时的总积分')),
                ('best_rank_at', models.DateTimeField(verbose_name='达成最佳名次时间')),
                ('best_score', models.FloatField(verbose_name='历史最高总积分')),
                ('best_score_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='最高总积分时的名次')),
                ('best_score_at', models.DateTimeField(verbose_name='达成最高总积分时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_record', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户最佳纪录',
                'verbose_name_plural': '用户最佳纪录',
            },
        ),
    ]
