# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客')], db_index=True, max_length=20, verbose_name='平台')),
                ('handle', models.CharField(max_length=100, verbose_name='平台账号标识')),
                ('handle_lower', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='小写标识')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='平台昵称')),
                ('verified', models.BooleanField(default=False, verbose_name='已验证归属')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
            ],
            options={
                'verbose_name': '平台账号',
                'verbose_name_plural': '平台账号',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('school_admin', '学校管理员'), ('super_admin', '超级管理员')], db_index=True, default='user', max_length=20, verbose_name='角色')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='真实姓名')),
                ('student_no', models.CharField(blank=True, max_length=50, verbose_name='学号')),
                ('passport_user_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='通行证用户ID')),
                ('school_bound_at', models.DateTimeField(blank=True, null=True, verbose_name='学校绑定时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
