# Generated by Django 5.2.17 on 2026-08-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='schools.school', verbose_name='所属学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_accounts', to='schools.school', verbose_name='归属学校'),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['school', 'role'], name='accounts_us_school__bd7735_idx'),
        ),
        migrations.AddIndex(
            model_name='platformaccount',
            index=models.Index(fields=['school', 'platform'], name='accounts_pl_school__fa5bd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'handle_lower'), name='uniq_platform_handle'),
        ),
        migrations.AddConstraint(
            model_name='platformaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='uniq_user_platform'),
        ),
    ]
