# Generated by Django 5.2.17 on 2026-08-04 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('system', '系统通知'), ('application_received', '管理员申请已提交'), ('application_reviewed', '管理员申请结果')], db_index=True, default='system', max_length=30, verbose_name='类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('message', models.TextField(blank=True, verbose_name='内容')),
                ('link', models.CharField(blank=True, help_text='前端路由，如 /admin/applications/12', max_length=255, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx')],
            },
        ),
    ]
