# Generated by Django 5.2.16 on 2026-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', '系统通知'), ('application_received', '管理员申请已提交'), ('application_reviewed', '管理员申请结果'), ('admin_message', '管理员消息')], db_index=True, default='system', max_length=30, verbose_name='类型'),
        ),
    ]
