# Generated by Django 5.2.16 on 2026-08-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='participated_contests',
            field=models.JSONField(blank=True, default=list, help_text='该账号参与过的比赛 external_id 列表', verbose_name='参与比赛索引'),
        ),
    ]
