# Generated by Django 5.2.16 on 2026-08-14 14:51

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_platformaccount_participated_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='连续登录失败次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近一次失败登录'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='锁定至'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_stamp',
            field=models.CharField(db_index=True, default=apps.accounts.models.generate_security_stamp, max_length=64, verbose_name='安全戳'),
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event_type', models.CharField(choices=[('login_success', '登录成功'), ('login_failure', '登录失败'), ('login_blocked', '登录被拦截(锁定/限流)'), ('logout', '登出'), ('account_locked', '账号锁定'), ('account_unlocked', '账号解锁'), ('anomaly', '异常行为')], db_index=True, max_length=20, verbose_name='事件')),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='尝试标识')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='客户端IP')),
                ('device_fp', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='设备指纹')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '认证日志',
                'verbose_name_plural': '认证日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7972e9_idx'), models.Index(fields=['identifier', 'created_at'], name='accounts_au_identif_b44e9a_idx'), models.Index(fields=['device_fp', 'created_at'], name='accounts_au_device__a34ed1_idx'), models.Index(fields=['ip', 'created_at'], name='accounts_au_ip_2e2e28_idx')],
            },
        ),
    ]
