# Generated by Django 5.2.17 on 2026-08-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_failed_login_count_user_last_failed_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='handle_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='handle 最近修改时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=200, verbose_name='个性签名'),
        ),
    ]
