# Generated by Django 5.2.16 on 2026-09-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_platformaccount_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandleAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('nowcoder', '牛客'), ('luogu', '洛谷')], db_index=True, max_length=20, verbose_name='平台')),
                ('handle', models.CharField(max_length=100, verbose_name='平台账号标识')),
                ('handle_lower', models.CharField(db_index=True, max_length=100, verbose_name='小写标识')),
                ('action', models.CharField(choices=[('user_bind', '用户自行绑定'), ('user_unbind', '用户自行解绑'), ('user_rebind', '用户改绑'), ('admin_bind', '管理端绑定'), ('admin_unbind', '管理端解绑'), ('admin_rebind', '管理端改绑')], db_index=True, max_length=20, verbose_name='动作')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handle_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handle_audits', to=settings.AUTH_USER_MODEL, verbose_name='当时的持有者')),
            ],
            options={
                'verbose_name': '绑定变动留痕',
                'verbose_name_plural': '绑定变动留痕',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'handle_lower', 'created_at'], name='accounts_ha_platfor_8fc4f4_idx')],
            },
        ),
    ]
