# Generated by Django 5.2.16 on 2026-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(choices=[('info', '普通'), ('success', '成功'), ('warning', '警告'), ('danger', '重要')], db_index=True, default='info', max_length=10, verbose_name='级别')),
                ('pinned', models.BooleanField(db_index=True, default=False, help_text='置顶公告始终排在最前', verbose_name='置顶')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='关闭后用户端不再展示，但记录保留可随时重新启用', verbose_name='启用')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
    ]
